# Generated by Django 4.2.1 on 2023-06-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='単価')),
            ],
            options={
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='注文日時')),
                ('amount', models.IntegerField(verbose_name='注文数')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.goods', verbose_name='注文商品')),
            ],
            options={
                'verbose_name': '注文',
            },
        ),
    ]
