# Generated by Django 4.2.1 on 2023-06-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文', 'verbose_name_plural': '注文'},
        ),
    ]
