# Generated by Django 4.2.1 on 2023-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_goods_options_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=999, verbose_name='注文番号'),
            preserve_default=False,
        ),
    ]
