# Generated by Django 4.2.1 on 2023-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(default='takashi', max_length=50, verbose_name='注文者'),
            preserve_default=False,
        ),
    ]
