# Generated by Django 4.2.1 on 2023-06-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_order_ordered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='discription',
            field=models.TextField(default='this is just a placeholder', max_length=500, verbose_name='説明'),
            preserve_default=False,
        ),
    ]
